zeros:
  joint1_pitch: -0.54
  joint1_yaw: 0.42
  joint2_pitch: 0.3
  joint2_yaw: 0.39
  joint3_pitch: -0.33
  joint3_yaw: 0.65
  joint4_pitch: -0.63
  joint4_yaw: 0.96
  joint5_pitch: -0.57
  joint5_yaw: 0.27
  joint6_pitch: 0.3
  joint6_yaw: 1.95
  joint7_pitch: 0.81
  joint7_yaw: 1.94
  joint8_pitch: 0.5
  joint8_yaw: 1.18
  joint9_pitch: 0.61
  joint9_yaw: 1.07
  joint10_pitch: 0.53
  joint10_yaw: 1.35
  joint11_pitch: 0.47
  joint11_yaw: 1.21
  joint12_pitch: 0.1
  joint12_yaw: 1.37
  joint13_pitch: 0.9
  joint13_yaw: 1.76
  joint14_pitch: 0.48
  joint14_yaw: 1.95
  joint15_pitch: 0.54
  joint15_yaw: 2.35