zeros:
  joint1_pitch: 0.5
  joint1_yaw: 2.3
  joint2_pitch: 0.5
  joint2_yaw: 2.3
  joint3_pitch: 0.5
  joint3_yaw: 2.3
  joint4_pitch: 0.5
  joint4_yaw: 2.3
  joint5_pitch: 0.5
  joint5_yaw: 2.3
  joint6_pitch: 0.5
  joint6_yaw: 2.3
  joint7_pitch: 0.5
  joint7_yaw: 2.3
  joint8_pitch: 0.5
  joint8_yaw: 2.3
  joint9_pitch: 0.5
  joint9_yaw: 2.3
  joint10_pitch: 0.5
  joint10_yaw: 2.3
  joint11_pitch: 0.5
  joint11_yaw: 2.3
  joint12_pitch: 0.5
  joint12_yaw: 2.3
  joint13_pitch: 0.5
  joint13_yaw: 2.3
  joint14_pitch: 0.5
  joint14_yaw: 2.3
  joint15_pitch: 0.5
  joint15_yaw: 2.3